services:
  tor-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ~/.ssh/id_rsa_ssh.pub:/home/kmahdi/.ssh/authorized_keys
    networks:
      - tor-network
    restart: unless-stopped

networks:
  tor-network:
    driver: bridge
