services:
  tor-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "3001:4242"
    networks:
      - tor-network
    restart: unless-stopped

networks:
  tor-network:
    driver: bridge
