services:
  tor-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tor-network
    restart: unless-stopped
    volumes:
      - ~/.ssh/id_rsa.pub:/home/kmahdi/.ssh/authorized_keys

networks:
  tor-network:
    driver: bridge
